# AI CLI Manager - Language Module
LANG = {
    'zh': {
        'title': 'AI CLI Manager v{}',
        'api_config': 'API 密钥配置',
        'prompts': '提示词',
        'prompt_builtin': '(内置)',
        'mcp': 'MCP 服务器',
        'add': '新增',
        'edit': '编辑',
        'delete': '删除',
        'copy': '复制',
        'save': '保存',
        'cancel': '取消',
        'name': '名称',
        'cli_type': 'CLI工具',
        'api_addr': 'API地址',
        'key_name': 'KEY名称',
        'api_key': 'API密钥',
        'terminal': '集成终端',
        'select_terminal': '选择终端',
        'python_env': 'Python环境',
        'work_dir': '工作目录',
        'browse': '浏览',
        'open_terminal': '打开终端',
        'copied': '已复制到剪贴板',
        'saved': '保存成功',
        'deleted': '删除成功',
        'confirm_delete': '确认删除',
        'confirm_delete_msg': '确定要删除 "{}" 吗？',
        'no_selection': '请先选择一项',
        'fill_required': '请填写必填项',
        'prompt_content': '提示词内容',
        'prompt_hint': '选择提示词后点击复制，可粘贴到任意位置使用',
        'mcp_command': '命令',
        'mcp_args': '参数',
        'mcp_env': '环境变量',
        'add_terminal': '+ 添加终端',
        'refresh_terminals': '刷新终端',
        'refresh_envs': '刷新环境',
        'current_key': '当前KEY:',
        'not_selected': '未选择',
        'terminals_refreshed': '终端列表已刷新',
        'envs_refreshed': 'Python环境已刷新，发现 {} 个环境',
        'move_up': '上移',
        'move_down': '下移',
        'export': '导出',
        'import': '导入',
        'feedback': '反馈: GitHub Issues',
        'copy_key': '复制',
        'exported_to': '配置已导出到: {}',
        'imported_count': '已导入 {} 个配置',
        'history': '历史记录',
        'history_sessions': '会话数',
        'history_messages': '消息数',
        'history_size': '占用空间',
        'history_refresh': '刷新',
        'history_delete': '删除',
        'history_trash': '回收站',
        'history_export': '导出MD',
        'history_copy_resume': '复制resume',
        'history_search': '搜索会话...',
        'history_old': '30天前 ({}个)',
        'history_confirm_delete': '确定删除 {} 个会话？\n会话将移动到回收站，{}天后自动清理。',
        'history_moved': '已移动 {} 个会话到回收站',
        'history_restored': '已恢复 {} 个会话',
        'history_trash_info': '回收站中的会话将在 {} 天后自动删除',
        'history_restore': '恢复',
        'history_perm_delete': '永久删除',
        'history_clear_trash': '清空回收站',
        'mcp_sync': '同步仓库',
        'mcp_browse': '浏览仓库',
        'mcp_import': '导入',
        'mcp_official': '官方推荐',
        'mcp_default_hint': '勾选设为默认 MCP（始终加载到全局和工作目录）',
        'mcp_search': '搜索',
        'mcp_category': '分类',
        'mcp_all': '全部',
        'mcp_selected': '已选: {}',
        'mcp_add_selected': '添加选中',
        'mcp_added': '已添加 {} 个 MCP',
        'mcp_sync_complete': '同步完成：共 {} 个 MCP，新增 {} 个',
        'mcp_sync_fail': '同步失败 - 调试信息',
        'mcp_sync_title': '同步 MCP 仓库',
        'mcp_sync_preparing': '准备同步...',
        'mcp_sync_sources': '从 PulseMCP、Smithery、GitHub 等源获取...',
        'mcp_set_default_hint': '设为默认（始终加载）',
        'mcp_import_title': '导入 MCP',
        'mcp_import_clipboard': '从剪贴板导入',
        'mcp_import_clipboard_desc': '直接粘贴 JSON 配置',
        'mcp_import_file': '从文件导入',
        'mcp_import_file_desc': '选择 .mcp.json 或其他 JSON 文件',
        'mcp_import_text': '从文本导入',
        'mcp_import_text_desc': '手动粘贴 JSON 文本',
        'mcp_import_format': '支持格式：{"mcpServers": {...}} 或 {"name": {...}}',
        'mcp_clipboard_empty': '剪贴板为空',
        'mcp_invalid_json': '剪贴板内容不是有效的 JSON',
        'mcp_no_valid_config': '未找到有效配置',
        'mcp_import_fail': '导入失败: {}',
        'mcp_select_official': '选择官方 MCP 服务器',
        'mcp_other': '其他',
        'mcp_cat_cloud': '云服务', 'mcp_cat_map': '地图', 'mcp_cat_media': '媒体', 'mcp_cat_security': '安全',
        'mcp_cat_tool': '工具', 'mcp_cat_dev': '开发', 'mcp_cat_search': '搜索', 'mcp_cat_db': '数据库',
        'mcp_cat_file': '文件', 'mcp_cat_news': '新闻', 'mcp_cat_calendar': '日历', 'mcp_cat_model': '模型',
        'mcp_cat_browser': '浏览器', 'mcp_cat_game': '游戏', 'mcp_cat_ecommerce': '电商', 'mcp_cat_knowledge': '知识库',
        'mcp_cat_social': '社交', 'mcp_cat_note': '笔记', 'mcp_cat_network': '网络', 'mcp_cat_design': '设计',
        'mcp_cat_comm': '通讯', 'mcp_cat_finance': '金融', 'mcp_cat_project': '项目', 'mcp_cat_other': '其他',
        'prompt_global': '全局提示词',
        'prompt_user': '用户提示词',
        'prompt_save_global': '保存全局提示词',
        'prompt_global_saved': '全局提示词已保存',
        'prompt_builtin_readonly': '内置提示词不可编辑',
        'prompt_apply': '应用提示词',
        'prompt_select_mcp': '选择 MCP',
        'prompt_select_workdir': '请先选择工作目录',
        'prompt_written': '已写入: {}',
        'prompt_write_fail': '写入失败: {}',
        'prompt_loaded': '已加载工作目录配置',
        'prompt_loaded_with': '已加载工作目录配置 | 提示词: {}',
        'prompt_no_config': '已选择工作目录（无现有配置）',
        'prompt_select_extra_mcp': '选择额外 MCP（默认 MCP 已自动加载）',
        'prompt_apply_btn': '应用',
        'history_session': '会话: {}',
        'history_path': '路径: {}',
        'history_copy_id': '复制ID',
        'history_export_md': '导出MD',
        'history_open_location': '打开位置',
        'history_expand_middle': '▼ 展开中间 {} 条消息 ▼',
        'history_no_content': '(无文本内容)',
        'history_tool': '[工具: {}]',
        'history_tool_result': '[工具结果]',
        'history_unknown': '未知',
        'history_unknown_date': '未知日期',
        'history_no_records': '无历史记录',
        'history_copied': '已复制: {}...',
        'history_exported': '已导出: {}',
        'history_click_hint': '点击选中，支持多选',
        'history_short_sessions': '短会话:',
        'history_empty_dirs': '空目录:',
        'history_cleanup': '清理会话',
        'history_cleanup_preview': '预��:',
        'history_cleanup_hint': '清理后会话将移至回收站',
        'history_cleanup_execute': '执行清理',
        'history_cleanup_done': '已清理 {} 个会话, {} 个空目录',
        'history_trash_cleared': '回收站已清空',
        'history_perm_deleted': '已永久删除 {} 个会话',
        'history_delete_selected': '删除选中',
        'history_delete_project': '删除此项目所有会话',
        'date_all': '全部',
        'date_today': '今天',
        'date_week': '本周',
        'date_month': '本月',
        'date_custom': '自定义',
        'date_from': '起始日期',
        'date_to': '结束日期',
        'terminal_issues': '检测到以下问题：',
        'terminal_continue': '继续启动',
        'toggle_theme': '切换主题',
        'switch_lang': '中/EN',
        'close': '关闭',
        'mcp_repo_title': 'MCP 仓库 ({} 个)',
        'mcp_updated': '更新: {}',
        'mcp_resync': '重新同步',
        'mcp_more_hint': '... 还有更多，请使用搜索缩小范围',
        'mcp_market': 'MCP市场',
        'mcp_not_synced': '未同步',
        'history_selected_count': '已选 {} 项',
        'history_short_label': '短会话（≤3条且≤150字）: {}个',
        'history_old_label': '30天前会话: {}个',
        'history_empty_label': '空项目目录: {}个',
        'custom': '自定义...',
        'custom_model': '自定义模型',
        'screenshot': '截图',
        'screenshot_saved': '截图已保存: {}',
        'pick_path': '复制路径',
        'path_copied': '路径已复制: {}',
        'validate_key': '验证',
        'validating': '验证中...',
        'validate_result': '验证结果: {}',
        'sync': '同步',
        'sync_settings': '云同步设置',
        'sync_token': 'GitHub Token',
        'sync_gist_id': 'Gist ID (留空自动创建)',
        'sync_upload': '上传配置',
        'sync_download': '下载配置',
        'sync_uploading': '正在上传...',
        'sync_downloading': '正在下载...',
        'sync_upload_ok': '上传成功，Gist ID: {}',
        'sync_download_ok': '下载成功，已导入 {} 个配置',
        'sync_fail': '同步失败: {}',
        'sync_no_token': '请先设置 GitHub Token',
        'export_html': '导出HTML',
        'export_md': '导出MD',
        'export_batch': '批量导出',
        'export_success': '导出成功: {}',
        'export_batch_success': '批量导出 {} 个会话到 {}',
        'clear_history': '清空历史',
        'history_cleared': '历史已清空',
        'tags': '标签',
        'minimize_to_tray': '最小化到托盘',
        'quota_url': '流量查询地址',
        'check_quota': '查询',
    },
    'en': {
        'title': 'AI CLI Manager v{}',
        'api_config': 'API Key Config',
        'prompts': 'Prompts',
        'prompt_builtin': '(Built-in)',
        'mcp': 'MCP Servers',
        'add': 'Add',
        'edit': 'Edit',
        'delete': 'Delete',
        'copy': 'Copy',
        'save': 'Save',
        'cancel': 'Cancel',
        'name': 'Name',
        'cli_type': 'CLI Tool',
        'api_addr': 'API Address',
        'key_name': 'KEY Name',
        'api_key': 'API Key',
        'terminal': 'Terminal',
        'select_terminal': 'Select Terminal',
        'python_env': 'Python Env',
        'work_dir': 'Work Directory',
        'browse': 'Browse',
        'open_terminal': 'Open Terminal',
        'copied': 'Copied to clipboard',
        'saved': 'Saved successfully',
        'deleted': 'Deleted successfully',
        'confirm_delete': 'Confirm Delete',
        'confirm_delete_msg': 'Are you sure to delete "{}"?',
        'no_selection': 'Please select an item first',
        'fill_required': 'Please fill in required fields',
        'prompt_content': 'Prompt Content',
        'prompt_hint': 'Select a prompt and click copy to use it anywhere',
        'mcp_command': 'Command',
        'mcp_args': 'Arguments',
        'mcp_env': 'Environment',
        'add_terminal': '+ Add Terminal',
        'refresh_terminals': 'Refresh Terminals',
        'refresh_envs': 'Refresh Envs',
        'current_key': 'Current KEY:',
        'not_selected': 'Not Selected',
        'terminals_refreshed': 'Terminal list refreshed',
        'envs_refreshed': 'Python envs refreshed, found {} envs',
        'move_up': 'Up',
        'move_down': 'Down',
        'export': 'Export',
        'import': 'Import',
        'feedback': 'Feedback: GitHub Issues',
        'copy_key': 'Copy',
        'exported_to': 'Config exported to: {}',
        'imported_count': 'Imported {} configs',
        'history': 'History',
        'history_sessions': 'Sessions',
        'history_messages': 'Messages',
        'history_size': 'Size',
        'history_refresh': 'Refresh',
        'history_delete': 'Delete',
        'history_trash': 'Trash',
        'history_export': 'Export MD',
        'history_copy_resume': 'Copy Resume',
        'history_search': 'Search sessions...',
        'history_old': 'Over 30 days ({})',
        'history_confirm_delete': 'Delete {} sessions?\nThey will be moved to trash and auto-deleted after {} days.',
        'history_moved': 'Moved {} sessions to trash',
        'history_restored': 'Restored {} sessions',
        'history_trash_info': 'Sessions in trash will be auto-deleted after {} days',
        'history_restore': 'Restore',
        'history_perm_delete': 'Delete Permanently',
        'history_clear_trash': 'Empty Trash',
        'mcp_sync': 'Sync Repository',
        'mcp_browse': 'Browse Repository',
        'mcp_import': 'Import',
        'mcp_official': 'Official',
        'mcp_default_hint': 'Check to set as default MCP (always loaded)',
        'mcp_search': 'Search',
        'mcp_category': 'Category',
        'mcp_all': 'All',
        'mcp_selected': 'Selected: {}',
        'mcp_add_selected': 'Add Selected',
        'mcp_added': 'Added {} MCP(s)',
        'mcp_sync_complete': 'Sync complete: {} MCPs, {} new',
        'mcp_sync_fail': 'Sync Failed - Debug Info',
        'mcp_sync_title': 'Sync MCP Repository',
        'mcp_sync_preparing': 'Preparing to sync...',
        'mcp_sync_sources': 'Fetching from PulseMCP, Smithery, GitHub...',
        'mcp_set_default_hint': 'Set as default (always load)',
        'mcp_import_title': 'Import MCP',
        'mcp_import_clipboard': 'From Clipboard',
        'mcp_import_clipboard_desc': 'Paste JSON config directly',
        'mcp_import_file': 'From File',
        'mcp_import_file_desc': 'Select .mcp.json or other JSON file',
        'mcp_import_text': 'From Text',
        'mcp_import_text_desc': 'Paste JSON text manually',
        'mcp_import_format': 'Format: {"mcpServers": {...}} or {"name": {...}}',
        'mcp_clipboard_empty': 'Clipboard is empty',
        'mcp_invalid_json': 'Invalid JSON in clipboard',
        'mcp_no_valid_config': 'No valid config found',
        'mcp_import_fail': 'Import failed: {}',
        'mcp_select_official': 'Select Official MCP Servers',
        'mcp_other': 'Other',
        'mcp_cat_cloud': 'Cloud', 'mcp_cat_map': 'Map', 'mcp_cat_media': 'Media', 'mcp_cat_security': 'Security',
        'mcp_cat_tool': 'Tools', 'mcp_cat_dev': 'Dev', 'mcp_cat_search': 'Search', 'mcp_cat_db': 'Database',
        'mcp_cat_file': 'File', 'mcp_cat_news': 'News', 'mcp_cat_calendar': 'Calendar', 'mcp_cat_model': 'Model',
        'mcp_cat_browser': 'Browser', 'mcp_cat_game': 'Game', 'mcp_cat_ecommerce': 'E-commerce', 'mcp_cat_knowledge': 'Knowledge',
        'mcp_cat_social': 'Social', 'mcp_cat_note': 'Note', 'mcp_cat_network': 'Network', 'mcp_cat_design': 'Design',
        'mcp_cat_comm': 'Comm', 'mcp_cat_finance': 'Finance', 'mcp_cat_project': 'Project', 'mcp_cat_other': 'Other',
        'prompt_global': 'Global Prompt',
        'prompt_user': 'User Prompts',
        'prompt_save_global': 'Save Global Prompt',
        'prompt_global_saved': 'Global prompt saved',
        'prompt_builtin_readonly': 'Built-in prompts are read-only',
        'prompt_apply': 'Apply Prompt',
        'prompt_select_mcp': 'Select MCP',
        'prompt_select_workdir': 'Please select work directory first',
        'prompt_written': 'Written to: {}',
        'prompt_write_fail': 'Write failed: {}',
        'prompt_loaded': 'Work directory config loaded',
        'prompt_loaded_with': 'Config loaded | Prompt: {}',
        'prompt_no_config': 'Work directory selected (no existing config)',
        'prompt_select_extra_mcp': 'Select extra MCP (default MCPs auto-loaded)',
        'prompt_apply_btn': 'Apply',
        'history_session': 'Session: {}',
        'history_path': 'Path: {}',
        'history_copy_id': 'Copy ID',
        'history_export_md': 'Export MD',
        'history_open_location': 'Open Location',
        'history_expand_middle': '▼ Expand {} messages ▼',
        'history_no_content': '(no text content)',
        'history_tool': '[Tool: {}]',
        'history_tool_result': '[Tool Result]',
        'history_unknown': 'Unknown',
        'history_unknown_date': 'Unknown Date',
        'history_no_records': 'No history records',
        'history_copied': 'Copied: {}...',
        'history_exported': 'Exported: {}',
        'history_click_hint': 'Click to select, multi-select supported',
        'history_short_sessions': 'Short sessions:',
        'history_empty_dirs': 'Empty directories:',
        'history_cleanup': 'Cleanup Sessions',
        'history_cleanup_preview': 'Preview:',
        'history_cleanup_hint': 'Sessions will be moved to trash',
        'history_cleanup_execute': 'Execute Cleanup',
        'history_cleanup_done': 'Cleaned {} sessions, {} empty dirs',
        'history_trash_cleared': 'Trash cleared',
        'history_perm_deleted': 'Permanently deleted {} sessions',
        'history_delete_selected': 'Delete Selected',
        'history_delete_project': 'Delete all sessions in project',
        'date_all': 'All',
        'date_today': 'Today',
        'date_week': 'This Week',
        'date_month': 'This Month',
        'date_custom': 'Custom',
        'date_from': 'From',
        'date_to': 'To',
        'terminal_issues': 'Issues detected:',
        'terminal_continue': 'Continue Anyway',
        'toggle_theme': 'Toggle Theme',
        'switch_lang': 'EN/中',
        'close': 'Close',
        'mcp_repo_title': 'MCP Repository ({})',
        'mcp_updated': 'Updated: {}',
        'mcp_resync': 'Re-sync',
        'mcp_more_hint': '... more results, use search to narrow down',
        'mcp_market': 'MCP Market',
        'mcp_not_synced': 'Not synced',
        'history_selected_count': 'Selected: {}',
        'history_short_label': 'Short sessions (≤3 msgs, ≤150 chars): {}',
        'history_old_label': 'Sessions over 30 days: {}',
        'history_empty_label': 'Empty project dirs: {}',
        'custom': 'Custom...',
        'custom_model': 'Custom Model',
        'screenshot': 'Screenshot',
        'screenshot_saved': 'Screenshot saved: {}',
        'pick_path': 'Copy Path',
        'path_copied': 'Path copied: {}',
        'validate_key': 'Validate',
        'validating': 'Validating...',
        'validate_result': 'Result: {}',
        'sync': 'Sync',
        'sync_settings': 'Cloud Sync Settings',
        'sync_token': 'GitHub Token',
        'sync_gist_id': 'Gist ID (leave empty to create)',
        'sync_upload': 'Upload',
        'sync_download': 'Download',
        'sync_uploading': 'Uploading...',
        'sync_downloading': 'Downloading...',
        'sync_upload_ok': 'Upload success, Gist ID: {}',
        'sync_download_ok': 'Downloaded {} configs',
        'sync_fail': 'Sync failed: {}',
        'sync_no_token': 'Please set GitHub Token first',
        'export_html': 'Export HTML',
        'export_md': 'Export MD',
        'export_batch': 'Batch Export',
        'export_success': 'Exported: {}',
        'export_batch_success': 'Exported {} sessions to {}',
        'clear_history': 'Clear History',
        'history_cleared': 'History cleared',
        'tags': 'Tags',
        'minimize_to_tray': 'Minimize to tray',
        'quota_url': 'Quota Check URL',
        'check_quota': 'Check',
    }
}
